export const DANG_NHAP_ACTION = 'DANG_NHAP_ACTION';
export const DANG_KY_ACTION = 'DANG_KY_ACTION';
export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG';

export const LAY_DANH_SACH_NGUOI_DUNG = 'LAY_DANH_SACH_NGUOI_DUNG';
export const LAY_DANH_SACH_NGUOI_DUNG_THEO_TU_KHOA = 'LAY_DANH_SACH_NGUOI_DUNG_THEO_TU_KHOA';

export const LAY_DANH_SACH_LOAI_NGUOI_DUNG = 'LAY_DANH_SACH_LOAI_NGUOI_DUNG';